# Homebrew formula for Wayang
# Generated by JReleaser

class Wayang < Formula
  desc "Wayang - AI Agent Workflow Platform"
  homepage "https://github.com/bhangun/wayang"
  version "{{projectVersion}}"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/bhangun/wayang/releases/download/v{{projectVersion}}/wayang-standalone-osx-aarch_64"
      sha256 "{{sha256_osx_aarch_64}}"
    else
      url "https://github.com/bhangun/wayang/releases/download/v{{projectVersion}}/wayang-standalone-osx-x86_64"
      sha256 "{{sha256_osx_x86_64}}"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/bhangun/wayang/releases/download/v{{projectVersion}}/wayang-standalone-linux-aarch_64"
      sha256 "{{sha256_linux_aarch_64}}"
    else
      url "https://github.com/bhangun/wayang/releases/download/v{{projectVersion}}/wayang-standalone-linux-x86_64"
      sha256 "{{sha256_linux_x86_64}}"
    end
  end

  def install
    bin.install Dir["wayang-standalone*"].first => "wayang"
  end

  test do
    output = shell_output("#{bin}/wayang --version 2>&1")
    assert_match "{{projectVersion}}", output
  end
end
