package tech.kayys.wayang.core.model;


/**
 * Audit event types
 */
enum AuditEventType {
    NODE_CREATED,
    NODE_LOADED,
    NODE_UNLOADED,
    EXECUTION_STARTED,
    EXECUTION_COMPLETED,
    EXECUTION_FAILED,
    VALIDATION_FAILED,
    QUOTA_EXCEEDED,
    SECURITY_VIOLATION,
    CAPABILITY_CHECK_FAILED,
    RESOURCE_LIMIT_EXCEEDED
}